### ISSUE TITLE
Правки problem_check

### ISSUE THREAD

**Issue by RisaMagpie** [SPbSUPractiseTeam/Data_Analysis#28]
https://github.com/SPbSUPractiseTeam/Data_Analysis/pull/30
Заменить в поле page значение path на referer (событие: edx.grades.problem.submitted )
(НЕ ЗАБЫТЬ ВНЕСТИ ПРАВКИ В ОБРАБОТЧИК ВНУТРИ АНАЛИЗА)

**Comment by N0fail** [comment]
Сделано
