### ISSUE TITLE
Правки problem_check

### ISSUE THREAD

**Issue by RisaMagpie** [SPbSUPractiseTeam/Data_Analysis#29]
https://github.com/SPbSUPractiseTeam/Data_Analysis/pull/30
Добавить поле в таблицу problem_check с названием блока вопросов 
Пример (из edx.grades.problem.submitted): 
"\u041f\u0440\u043e\u0432\u0435\u0440\u043e\u0447\u043d\u044b\u0435 \u0432\u043e\u043f\u0440\u043e\u0441\u044b \u043a \u0443\u0440\u043e\u043a\u0443 1"
это url код:
"Проверочные вопросы к уроку  1"
Конвертер: http://www.abakbot.ru/online-5/225-dekodirovat-tekst-u0xxx-onlajn

После этого в анализе надо добавить обработку этого поля!

**Comment by N0fail** [comment]
Поле добавлено
