### ISSUE TITLE
Процент просмотренного видео

### ISSUE THREAD

**Issue by IceWind2** [SPbSUPractiseTeam/Data_Analysis#7]
[Описание](https://docs.google.com/document/d/1Sx9AgpWq1u88boltRs073ZWRQ2lGlq5IG-Jk-mHRkHA/edit) : модуль видео 1

**Comment by DavydovDmitry** [comment]
![image](https://user-images.githubusercontent.com/21951946/47676238-1a404b80-dbcd-11e8-8b05-8847b4e87a60.png)
