### ISSUE TITLE
Нахождение пересматриваемых моментов видео

### ISSUE THREAD

**Issue by IceWind2** [SPbSUPractiseTeam/Data_Analysis#8]
[Описание](https://docs.google.com/document/d/1Sx9AgpWq1u88boltRs073ZWRQ2lGlq5IG-Jk-mHRkHA/edit) : модуль видео пункт 2

**Comment by DavydovDmitry** [comment]
![image](https://user-images.githubusercontent.com/21951946/47676669-4dcfa580-dbce-11e8-87d6-cede26232ce6.png)
set fields intervals_number and review_intervals (how many times people watch interval again). By its we show the graph

**Comment by DavydovDmitry** [comment]
Find out at what intervals to split video
