### ISSUE TITLE
Посчитать статистику для тестов

### ISSUE THREAD

**Issue by IceWind2** [SPbSUPractiseTeam/Data_Analysis#9]
[Описание](https://docs.google.com/document/d/1Sx9AgpWq1u88boltRs073ZWRQ2lGlq5IG-Jk-mHRkHA/edit) : модуль тестов 1
https://github.com/SPbSUPractiseTeam/Data_Analysis/pull/18

**Comment by RisaMagpie** [comment]
- [x] среднее значение результатов теста
- [ ] среднее время прохождения теста - проблема: https://github.com/SPbSUPractiseTeam/Data_Analysis/issues/17
- [x] процент правильных ответов на вопрос
